version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building Next.js application..."
      - npm run build

  post_build:
    commands:
      - echo "Build completed. Preparing artifacts..."
      # - mkdir -p build_output
      # - cp -r .next static public package.json next.config.js build_output/

artifacts:
  files:
    - "**/*"
  name: nextjs-build-output
