version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci # Ensures a clean install based on package-lock.json

  build:
    commands:
      - echo "Building Next.js application..."
      - npm run build

  # post_build:
  #   commands:
  #     - echo "Zipping deployment package for Elastic Beanstalk..."
  #     - zip -r next-deploy.zip . -x "node_modules/*" ".git/*" "buildspec.yml"

artifacts:
  files:
    - "**/*"
