version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci # Ensures a clean install based on package-lock.json

  build:
    commands:
      - echo "Building Next.js application..."
      - npm run build

  post_build:
    commands:
      - echo "Preparing deployment package..."
      - mkdir -p build_output
      - cp -r .next node_modules public package.json next.config.js build_output/
      - zip -r nextjs-deploy.zip build_output/*

artifacts:
  files:
    - nextjs-deploy.zip
